import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import DappProvider from "@/providers/DappProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <DappProvider>
      <html lang="en">
        <body className={`${geistSans.variable} antialiased`}>
          {children}

          <Toaster position="top-right" />
        </body>
      </html>
    </DappProvider>

  );
}
